# 1マスターノード、3ワーカーノード
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.17.0@sha256:9512edae126da271b66b990b6fff768fbb7cd786c7d39e86bdf55906352fdf62
  kubeadmConfigPatches:
    - |
      kind: ClusterConfiguration
      apiServer:
        extraArgs:
          "feature-gates": "EvenPodsSpread=true"
      scheduler:
        extraArgs:
          "feature-gates": "EvenPodsSpread=true"
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "region=asia-northeast1,zone=asia-northeast1-a,ingress-ready=true"
          authorization-mode: "AlwaysAllow"
# ワーカーノードはマルチリージョンで稼働している想定でラベルを付与
# Tokyo Regionで同一zoneに3ノードを配置
- role: worker
  image: kindest/node:v1.17.0@sha256:9512edae126da271b66b990b6fff768fbb7cd786c7d39e86bdf55906352fdf62
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "region=asia-northeast1,zone=asia-northeast1-a"
- role: worker
  image: kindest/node:v1.17.0@sha256:9512edae126da271b66b990b6fff768fbb7cd786c7d39e86bdf55906352fdf62
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "region=asia-northeast1,zone=asia-northeast1-a"
- role: worker
  image: kindest/node:v1.17.0@sha256:9512edae126da271b66b990b6fff768fbb7cd786c7d39e86bdf55906352fdf62
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "region=asia-northeast1,zone=asia-northeast1-a"
