# シングルノード版マニフェスト
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
metadata:
  name: kind-single
  labels:
    env: kind
nodes:
  - role: control-plane
    image: kindest/node:v1.18.8@sha256:d07837014dd00b1ef35019212f268a2d16436721761ce3eeb0b38a03b536b924
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            "feature-gates": "EvenPodsSpread=true"
        scheduler:
          extraArgs:
            "feature-gates": "EvenPodsSpread=true"
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "region=asia-northeast1,zone=asia-northeast1-a,ingress-ready=true"
            authorization-mode: "AlwaysAllow"
  # ワーカーノードは東京リージョンで稼働している想定でラベルを付与
  - role: worker
    image: kindest/node:v1.18.8@sha256:d07837014dd00b1ef35019212f268a2d16436721761ce3eeb0b38a03b536b924
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "region=asia-northeast1,zone=asia-northeast1-a"
