name: Kubernetes Manifest CI

on:
  push:

jobs:
  kubeval:
    name: DockerHub Uses Test
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
        working-directory: ./manifests

    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v2

      - name: KubeVal
        id: kubeval
        uses: docker://garethr/kubeval:0.15.0
        env:
          KUBERNETES_VERSION: 1.18.0
        with:
          args: -d . -v ${{ env.KUBERNETES_VERSION }} --strict --force-color
